-- Product Compatibility (15 tags)
INSERT INTO tag_definitions (category_id, tag_key, display_name, description, sort_order, tag_type)
SELECT id, 'wall_art', 'Wall Art', 'Framed prints, canvas, posters', 10, 'system' FROM category_definitions WHERE category_key = 'product_compatibility'
UNION ALL SELECT id, 'textile', 'Textile', 'Fabric and soft goods', 20, 'system' FROM category_definitions WHERE category_key = 'product_compatibility'
UNION ALL SELECT id, 'home_decor', 'Home Decor', 'Decorative accessories', 30, 'system' FROM category_definitions WHERE category_key = 'product_compatibility'
UNION ALL SELECT id, 'stationery', 'Stationery', 'Paper goods and cards', 40, 'system' FROM category_definitions WHERE category_key = 'product_compatibility'
UNION ALL SELECT id, 'apparel', 'Apparel', 'Clothing and wearables', 50, 'system' FROM category_definitions WHERE category_key = 'product_compatibility'
UNION ALL SELECT id, 'packaging', 'Packaging', 'Product packaging design', 60, 'system' FROM category_definitions WHERE category_key = 'product_compatibility'
UNION ALL SELECT id, 'wallpaper', 'Wallpaper', 'Wall covering patterns', 70, 'system' FROM category_definitions WHERE category_key = 'product_compatibility'
UNION ALL SELECT id, 'bedding', 'Bedding', 'Sheets, pillows, comforters', 80, 'system' FROM category_definitions WHERE category_key = 'product_compatibility'
UNION ALL SELECT id, 'tableware', 'Tableware', 'Dishes, mugs, serving', 90, 'system' FROM category_definitions WHERE category_key = 'product_compatibility'
UNION ALL SELECT id, 'tech_accessories', 'Tech Accessories', 'Phone cases, laptop skins', 100, 'system' FROM category_definitions WHERE category_key = 'product_compatibility'
UNION ALL SELECT id, 'greeting_cards', 'Greeting Cards', 'Cards and postcards', 110, 'system' FROM category_definitions WHERE category_key = 'product_compatibility'
UNION ALL SELECT id, 'calendar', 'Calendar', 'Wall and desk calendars', 120, 'system' FROM category_definitions WHERE category_key = 'product_compatibility'
UNION ALL SELECT id, 'book_cover', 'Book Cover', 'Book and journal covers', 130, 'system' FROM category_definitions WHERE category_key = 'product_compatibility'
UNION ALL SELECT id, 'tote_bag', 'Tote Bag', 'Reusable shopping bags', 140, 'system' FROM category_definitions WHERE category_key = 'product_compatibility'
UNION ALL SELECT id, 'puzzle', 'Puzzle', 'Jigsaw puzzles', 150, 'system' FROM category_definitions WHERE category_key = 'product_compatibility';

-- Size Category + Orientation + Target Market (25 tags total)
INSERT INTO tag_definitions (category_id, tag_key, display_name, description, sort_order, tag_type)
SELECT id, 'small', 'Small', '8x10" to 11x14"', 10, 'system' FROM category_definitions WHERE category_key = 'size_category'
UNION ALL SELECT id, 'medium', 'Medium', '16x20" to 18x24"', 20, 'system' FROM category_definitions WHERE category_key = 'size_category'
UNION ALL SELECT id, 'large', 'Large', '24x36" to 30x40"', 30, 'system' FROM category_definitions WHERE category_key = 'size_category'
UNION ALL SELECT id, 'oversized', 'Oversized', '40x60" and above', 40, 'system' FROM category_definitions WHERE category_key = 'size_category'
UNION ALL SELECT id, 'square_small', 'Square Small', '12x12" to 16x16"', 50, 'system' FROM category_definitions WHERE category_key = 'size_category'
UNION ALL SELECT id, 'square_large', 'Square Large', '20x20" to 36x36"', 60, 'system' FROM category_definitions WHERE category_key = 'size_category'
UNION ALL SELECT id, 'panoramic', 'Panoramic', 'Wide aspect ratios', 70, 'system' FROM category_definitions WHERE category_key = 'size_category'
UNION ALL SELECT id, 'miniature', 'Miniature', 'Under 8x10"', 80, 'system' FROM category_definitions WHERE category_key = 'size_category'
UNION ALL SELECT id, 'portrait', 'Portrait', 'Vertical orientation', 10, 'system' FROM category_definitions WHERE category_key = 'orientation'
UNION ALL SELECT id, 'landscape', 'Landscape', 'Horizontal orientation', 20, 'system' FROM category_definitions WHERE category_key = 'orientation'
UNION ALL SELECT id, 'square', 'Square', 'Equal dimensions', 30, 'system' FROM category_definitions WHERE category_key = 'orientation'
UNION ALL SELECT id, 'panoramic_wide', 'Panoramic', 'Extra wide horizontal', 40, 'system' FROM category_definitions WHERE category_key = 'orientation'
UNION ALL SELECT id, 'vertical_panoramic', 'Vertical Panoramic', 'Extra tall vertical', 50, 'system' FROM category_definitions WHERE category_key = 'orientation'
UNION ALL SELECT id, 'residential', 'Residential', 'Home consumers', 10, 'system' FROM category_definitions WHERE category_key = 'target_market'
UNION ALL SELECT id, 'commercial', 'Commercial', 'Business buyers', 20, 'system' FROM category_definitions WHERE category_key = 'target_market'
UNION ALL SELECT id, 'hospitality_market', 'Hospitality', 'Hotels and resorts', 30, 'system' FROM category_definitions WHERE category_key = 'target_market'
UNION ALL SELECT id, 'corporate', 'Corporate', 'Corporate offices', 40, 'system' FROM category_definitions WHERE category_key = 'target_market'
UNION ALL SELECT id, 'healthcare_market', 'Healthcare', 'Medical facilities', 50, 'system' FROM category_definitions WHERE category_key = 'target_market'
UNION ALL SELECT id, 'designer', 'Interior Designer', 'Design professionals', 60, 'system' FROM category_definitions WHERE category_key = 'target_market'
UNION ALL SELECT id, 'architect', 'Architect', 'Architecture firms', 70, 'system' FROM category_definitions WHERE category_key = 'target_market'
UNION ALL SELECT id, 'developer', 'Developer', 'Real estate developers', 80, 'system' FROM category_definitions WHERE category_key = 'target_market'
UNION ALL SELECT id, 'boutique', 'Boutique', 'Small retail shops', 90, 'system' FROM category_definitions WHERE category_key = 'target_market'
UNION ALL SELECT id, 'mass_market', 'Mass Market', 'Big box retailers', 100, 'system' FROM category_definitions WHERE category_key = 'target_market'
UNION ALL SELECT id, 'luxury_market', 'Luxury', 'High-end consumers', 110, 'system' FROM category_definitions WHERE category_key = 'target_market'
UNION ALL SELECT id, 'budget', 'Budget', 'Value-conscious buyers', 120, 'system' FROM category_definitions WHERE category_key = 'target_market';