-- Industry Focus (12 tags) + Geographic Style (12 tags)
INSERT INTO tag_definitions (category_id, tag_key, display_name, description, sort_order, tag_type)
SELECT id, 'home_decor_industry', 'Home Decor', 'Interior design products', 10, 'system' FROM category_definitions WHERE category_key = 'industry_focus'
UNION ALL SELECT id, 'fashion', 'Fashion', 'Apparel and accessories', 20, 'system' FROM category_definitions WHERE category_key = 'industry_focus'
UNION ALL SELECT id, 'hospitality_industry', 'Hospitality', 'Hotels and travel', 30, 'system' FROM category_definitions WHERE category_key = 'industry_focus'
UNION ALL SELECT id, 'tech', 'Tech', 'Technology products', 40, 'system' FROM category_definitions WHERE category_key = 'industry_focus'
UNION ALL SELECT id, 'beauty', 'Beauty', 'Cosmetics and wellness', 50, 'system' FROM category_definitions WHERE category_key = 'industry_focus'
UNION ALL SELECT id, 'food_beverage', 'Food & Beverage', 'Culinary industry', 60, 'system' FROM category_definitions WHERE category_key = 'industry_focus'
UNION ALL SELECT id, 'publishing', 'Publishing', 'Books and media', 70, 'system' FROM category_definitions WHERE category_key = 'industry_focus'
UNION ALL SELECT id, 'stationery_industry', 'Stationery', 'Paper goods', 80, 'system' FROM category_definitions WHERE category_key = 'industry_focus'
UNION ALL SELECT id, 'gift', 'Gift', 'Gift products', 90, 'system' FROM category_definitions WHERE category_key = 'industry_focus'
UNION ALL SELECT id, 'lifestyle', 'Lifestyle', 'Lifestyle brands', 100, 'system' FROM category_definitions WHERE category_key = 'industry_focus'
UNION ALL SELECT id, 'wellness_industry', 'Wellness', 'Health and fitness', 110, 'system' FROM category_definitions WHERE category_key = 'industry_focus'
UNION ALL SELECT id, 'children', 'Children', 'Kids products', 120, 'system' FROM category_definitions WHERE category_key = 'industry_focus'
UNION ALL SELECT id, 'scandinavian_style', 'Scandinavian', 'Nordic minimalism', 10, 'system' FROM category_definitions WHERE category_key = 'geographic_style'
UNION ALL SELECT id, 'mediterranean', 'Mediterranean', 'Coastal European style', 20, 'system' FROM category_definitions WHERE category_key = 'geographic_style'
UNION ALL SELECT id, 'coastal_style', 'Coastal', 'Beach and ocean aesthetic', 30, 'system' FROM category_definitions WHERE category_key = 'geographic_style'
UNION ALL SELECT id, 'japanese', 'Japanese', 'Eastern minimalism', 40, 'system' FROM category_definitions WHERE category_key = 'geographic_style'
UNION ALL SELECT id, 'moroccan', 'Moroccan', 'North African patterns', 50, 'system' FROM category_definitions WHERE category_key = 'geographic_style'
UNION ALL SELECT id, 'french', 'French', 'Parisian elegance', 60, 'system' FROM category_definitions WHERE category_key = 'geographic_style'
UNION ALL SELECT id, 'tropical_style', 'Tropical', 'Lush and vibrant', 70, 'system' FROM category_definitions WHERE category_key = 'geographic_style'
UNION ALL SELECT id, 'southwestern', 'Southwestern', 'Desert and adobe style', 80, 'system' FROM category_definitions WHERE category_key = 'geographic_style'
UNION ALL SELECT id, 'asian_fusion', 'Asian Fusion', 'Pan-Asian blend', 90, 'system' FROM category_definitions WHERE category_key = 'geographic_style'
UNION ALL SELECT id, 'latin', 'Latin', 'Latin American vibrancy', 100, 'system' FROM category_definitions WHERE category_key = 'geographic_style'
UNION ALL SELECT id, 'british', 'British', 'English countryside', 110, 'system' FROM category_definitions WHERE category_key = 'geographic_style'
UNION ALL SELECT id, 'australian', 'Australian', 'Relaxed coastal living', 120, 'system' FROM category_definitions WHERE category_key = 'geographic_style';