-- Mood & Emotion (25 tags)
INSERT INTO tag_definitions (category_id, tag_key, display_name, description, sort_order, tag_type)
SELECT id, 'calm', 'Calm', 'Peaceful, serene, tranquil', 10, 'system' FROM category_definitions WHERE category_key = 'mood_emotion'
UNION ALL SELECT id, 'energetic', 'Energetic', 'Dynamic, lively, vigorous', 20, 'system' FROM category_definitions WHERE category_key = 'mood_emotion'
UNION ALL SELECT id, 'romantic', 'Romantic', 'Loving, tender, affectionate', 30, 'system' FROM category_definitions WHERE category_key = 'mood_emotion'
UNION ALL SELECT id, 'melancholic', 'Melancholic', 'Pensive, reflective, wistful', 40, 'system' FROM category_definitions WHERE category_key = 'mood_emotion'
UNION ALL SELECT id, 'joyful', 'Joyful', 'Happy, cheerful, uplifting', 50, 'system' FROM category_definitions WHERE category_key = 'mood_emotion'
UNION ALL SELECT id, 'mysterious', 'Mysterious', 'Enigmatic, intriguing, cryptic', 60, 'system' FROM category_definitions WHERE category_key = 'mood_emotion'
UNION ALL SELECT id, 'dramatic', 'Dramatic', 'Intense, bold, striking', 70, 'system' FROM category_definitions WHERE category_key = 'mood_emotion'
UNION ALL SELECT id, 'peaceful', 'Peaceful', 'Harmonious, restful, quiet', 80, 'system' FROM category_definitions WHERE category_key = 'mood_emotion'
UNION ALL SELECT id, 'playful', 'Playful', 'Fun, lighthearted, whimsical', 90, 'system' FROM category_definitions WHERE category_key = 'mood_emotion'
UNION ALL SELECT id, 'sophisticated', 'Sophisticated', 'Refined, elegant, cultured', 100, 'system' FROM category_definitions WHERE category_key = 'mood_emotion'
UNION ALL SELECT id, 'nostalgic', 'Nostalgic', 'Sentimental, reminiscent', 110, 'system' FROM category_definitions WHERE category_key = 'mood_emotion'
UNION ALL SELECT id, 'inspirational', 'Inspirational', 'Motivating, uplifting, encouraging', 120, 'system' FROM category_definitions WHERE category_key = 'mood_emotion'
UNION ALL SELECT id, 'contemplative', 'Contemplative', 'Thoughtful, meditative, reflective', 130, 'system' FROM category_definitions WHERE category_key = 'mood_emotion'
UNION ALL SELECT id, 'bold', 'Bold', 'Confident, assertive, strong', 140, 'system' FROM category_definitions WHERE category_key = 'mood_emotion'
UNION ALL SELECT id, 'delicate', 'Delicate', 'Gentle, subtle, refined', 150, 'system' FROM category_definitions WHERE category_key = 'mood_emotion'
UNION ALL SELECT id, 'cozy', 'Cozy', 'Warm, comfortable, inviting', 160, 'system' FROM category_definitions WHERE category_key = 'mood_emotion'
UNION ALL SELECT id, 'fresh', 'Fresh', 'Clean, crisp, invigorating', 170, 'system' FROM category_definitions WHERE category_key = 'mood_emotion'
UNION ALL SELECT id, 'ethereal', 'Ethereal', 'Otherworldly, dreamy, light', 180, 'system' FROM category_definitions WHERE category_key = 'mood_emotion'
UNION ALL SELECT id, 'powerful', 'Powerful', 'Strong, commanding, impactful', 190, 'system' FROM category_definitions WHERE category_key = 'mood_emotion'
UNION ALL SELECT id, 'gentle', 'Gentle', 'Soft, mild, tender', 200, 'system' FROM category_definitions WHERE category_key = 'mood_emotion'
UNION ALL SELECT id, 'luxurious', 'Luxurious', 'Opulent, lavish, premium', 210, 'system' FROM category_definitions WHERE category_key = 'mood_emotion'
UNION ALL SELECT id, 'rustic', 'Rustic', 'Natural, simple, earthy', 220, 'system' FROM category_definitions WHERE category_key = 'mood_emotion'
UNION ALL SELECT id, 'elegant', 'Elegant', 'Graceful, refined, tasteful', 230, 'system' FROM category_definitions WHERE category_key = 'mood_emotion'
UNION ALL SELECT id, 'edgy', 'Edgy', 'Unconventional, bold, modern', 240, 'system' FROM category_definitions WHERE category_key = 'mood_emotion'
UNION ALL SELECT id, 'zen', 'Zen', 'Balanced, meditative, harmonious', 250, 'system' FROM category_definitions WHERE category_key = 'mood_emotion';