-- Core Artwork Tags: Artistic Style (25 tags)
INSERT INTO tag_definitions (category_id, tag_key, display_name, description, sort_order, tag_type)
SELECT id, 'abstract', 'Abstract', 'Non-representational art focusing on color, form, and texture', 10, 'system' FROM category_definitions WHERE category_key = 'artistic_style'
UNION ALL SELECT id, 'impressionist', 'Impressionist', 'Loose brushwork capturing light and moment', 20, 'system' FROM category_definitions WHERE category_key = 'artistic_style'
UNION ALL SELECT id, 'minimalist', 'Minimalist', 'Simple, clean lines with minimal elements', 30, 'system' FROM category_definitions WHERE category_key = 'artistic_style'
UNION ALL SELECT id, 'geometric', 'Geometric', 'Shapes, patterns, and mathematical precision', 40, 'system' FROM category_definitions WHERE category_key = 'artistic_style'
UNION ALL SELECT id, 'organic', 'Organic', 'Natural, flowing forms inspired by nature', 50, 'system' FROM category_definitions WHERE category_key = 'artistic_style'
UNION ALL SELECT id, 'contemporary', 'Contemporary', 'Modern artistic approaches and trends', 60, 'system' FROM category_definitions WHERE category_key = 'artistic_style'
UNION ALL SELECT id, 'realistic', 'Realistic', 'Detailed representation of subjects', 70, 'system' FROM category_definitions WHERE category_key = 'artistic_style'
UNION ALL SELECT id, 'expressionist', 'Expressionist', 'Emotional intensity and bold color', 80, 'system' FROM category_definitions WHERE category_key = 'artistic_style'
UNION ALL SELECT id, 'surrealist', 'Surrealist', 'Dream-like, unexpected combinations', 90, 'system' FROM category_definitions WHERE category_key = 'artistic_style'
UNION ALL SELECT id, 'pop_art', 'Pop Art', 'Bold colors, mass culture references', 100, 'system' FROM category_definitions WHERE category_key = 'artistic_style'
UNION ALL SELECT id, 'art_deco', 'Art Deco', 'Geometric elegance, luxury aesthetic', 110, 'system' FROM category_definitions WHERE category_key = 'artistic_style'
UNION ALL SELECT id, 'art_nouveau', 'Art Nouveau', 'Flowing lines, natural forms', 120, 'system' FROM category_definitions WHERE category_key = 'artistic_style'
UNION ALL SELECT id, 'cubist', 'Cubist', 'Fragmented, multi-perspective forms', 130, 'system' FROM category_definitions WHERE category_key = 'artistic_style'
UNION ALL SELECT id, 'folk_art', 'Folk Art', 'Traditional, cultural patterns', 140, 'system' FROM category_definitions WHERE category_key = 'artistic_style'
UNION ALL SELECT id, 'naive', 'Naive', 'Childlike simplicity and directness', 150, 'system' FROM category_definitions WHERE category_key = 'artistic_style'
UNION ALL SELECT id, 'modernist', 'Modernist', 'Clean, functional aesthetic', 160, 'system' FROM category_definitions WHERE category_key = 'artistic_style'
UNION ALL SELECT id, 'postmodern', 'Postmodern', 'Eclectic, ironic, mixed styles', 170, 'system' FROM category_definitions WHERE category_key = 'artistic_style'
UNION ALL SELECT id, 'vintage', 'Vintage', 'Classic, nostalgic aesthetic', 180, 'system' FROM category_definitions WHERE category_key = 'artistic_style'
UNION ALL SELECT id, 'retro', 'Retro', 'Mid-century modern influence', 190, 'system' FROM category_definitions WHERE category_key = 'artistic_style'
UNION ALL SELECT id, 'boho', 'Bohemian', 'Free-spirited, eclectic mix', 200, 'system' FROM category_definitions WHERE category_key = 'artistic_style'
UNION ALL SELECT id, 'scandinavian', 'Scandinavian', 'Clean, functional, natural', 210, 'system' FROM category_definitions WHERE category_key = 'artistic_style'
UNION ALL SELECT id, 'industrial', 'Industrial', 'Raw, urban, mechanical', 220, 'system' FROM category_definitions WHERE category_key = 'artistic_style'
UNION ALL SELECT id, 'grunge', 'Grunge', 'Distressed, textured, urban edge', 230, 'system' FROM category_definitions WHERE category_key = 'artistic_style'
UNION ALL SELECT id, 'whimsical', 'Whimsical', 'Playful, imaginative, lighthearted', 240, 'system' FROM category_definitions WHERE category_key = 'artistic_style'
UNION ALL SELECT id, 'luxury', 'Luxury', 'Opulent, refined, premium', 250, 'system' FROM category_definitions WHERE category_key = 'artistic_style';